name: CI

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        sudo gem install ceedling
        pip install gcovr

    - name: Build blinky
      run: |
        make BOARD=pcSim PROJECT_PATH=examples/blinky
        
    - name: Run tests
      run: |
        ./run_all_tests.sh

    - name: Save coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: out/testReport

