name: CI

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        sudo gem install ceedling
        pip install gcovr

    - name: Run tests
      run: |
        ./run_all_tests.sh

