name: CI

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        sudo gem install ceedling
        pip install gcovr
        sudo apt install gprbuild
        sudo apt install gnat

    - name: Build blinky
      run: |
        make clean
        make BOARD=pcSim PROJECT_PATH=examples/blinky

    - name: Build example_cpp
      run: |
        make clean
        make BOARD=pcSim PROJECT_PATH=examples/example_cpp

    - name: Build blinky Ada
      run: |
        make clean
        make BOARD=pcSim PROJECT_PATH=examples/ada/blinky ada_build
        make BOARD=pcSim PROJECT_PATH=examples/ada/blinky

    - name: Run tests
      run: |
        ./run_all_tests.sh

    - name: Save coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: out/testReport

